PW Field to User table
rooftopsparrow/ledger pull request #52
Opened 2021-03-31 20:11 UTC by BProw

Hashed pw field to User table

2021-04-07 19:34 UTC, rooftopsparrow requested changes

2021-04-07 19:34 UTC, rooftopsparrow commented on repos/user.go
> +	PW 		  string 	`pg:",notnull,unique"`
PW does not need to be unique across rows.

2021-04-07 19:34 UTC, rooftopsparrow commented on web/api.go
> +											  pwEncyrpted)
weird formatting?

2021-04-07 22:27 UTC, BProw commented
Thanks! Will update w/ changes reflected shortly.

2021-04-07 23:09 UTC, BProw reviewed
Should now be complete. Formatting is strange, what tool do you use for formatting go files in vsc?

2021-04-09 21:35 UTC, rooftopsparrow commented
Run `go fmt` to fix go files.

2021-04-09 21:36 UTC, rooftopsparrow commented
It looks like the tests are failing too. The tests are using the CreateUser call, should be a simple update.

2021-04-10 04:34 UTC, BProw commented
> Run `go fmt` to fix go files.

Thanks! This should work.

> It looks like the tests are failing too. The tests are using the CreateUser call, should be a simple update.

Error when trying to test changes to CreateUser call in feature_test.go:

panic: FATAL #28P01 password authentication failed for user "postgres"

I made sure env password is correct. Currently stuck troubleshooting. Any recommendations?

2021-04-12 02:17 UTC, rooftopsparrow commented
I assume its environment variable issue. Try pushing your code against the CI using it's environment variables.

2021-04-12 04:51 UTC, BProw commented
> I assume its environment variable issue. Try pushing your code against the CI using it's environment variables.

Definitely agree. I think I already have? Not confident. If you're available this week to chat about this, let me know.

2021-04-12 18:07 UTC, rooftopsparrow commented
> Definitely agree. I think I already have?

Ok the error I see in CI is:

```
Error: ./feature_test.go:131:8: no new variables on left side of :=
```

Not anything about environment variables

2021-04-18 21:08 UTC, merged